// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCs_3NvLA3qTrlix8y3D_sBd8ilQcf_vQg',
    appId: '1:595855593593:web:2cf919ebe4f45a1d2a44a8',
    messagingSenderId: '595855593593',
    projectId: 'heamed-1d38d',
    authDomain: 'heamed-1d38d.firebaseapp.com',
    storageBucket: 'heamed-1d38d.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAcNFLR-htfEbZ6CWW-5fLQNOh65vCL9aI',
    appId: '1:595855593593:android:7cab084be8ea5db22a44a8',
    messagingSenderId: '595855593593',
    projectId: 'heamed-1d38d',
    storageBucket: 'heamed-1d38d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB8sPQBp8Ne4V-L9J8EiQBA6jsxuqyZsM4',
    appId: '1:595855593593:ios:a0aa448900347e2c2a44a8',
    messagingSenderId: '595855593593',
    projectId: 'heamed-1d38d',
    storageBucket: 'heamed-1d38d.appspot.com',
    iosBundleId: 'com.example.heamed',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB8sPQBp8Ne4V-L9J8EiQBA6jsxuqyZsM4',
    appId: '1:595855593593:ios:3d48a17589fabae72a44a8',
    messagingSenderId: '595855593593',
    projectId: 'heamed-1d38d',
    storageBucket: 'heamed-1d38d.appspot.com',
    iosBundleId: 'com.example.heamed.RunnerTests',
  );
}
